import { createContext, useContext, useState } from 'react'

const translations = {
  en: {
    // ── Nav ──────────────────────────────────────────
    home:              'Home',
    aboutUs:           'About Us',
    anthropology:      'Anthropology',
    donation:          'Donation',
    allProjects:       'All Projects',
    education:         'Education',
    health:            'Health',
    infra:             'Infrastructure',
    pages:             'Pages',
    ourTeam:           'Our Team',
    gallery:           'Gallery',
    faq:               'FAQ',
    diaspora:          'Diaspora Map',
    volunteers:        'Volunteers',
    events:            'Events',
    news:              'News',
    contact:           'Contact',
    donateNow:         'Donate Now',
    login:             'Login',
    logout:            'Logout',
    myDashboard:       'My Dashboard',
    profile:           'Profile',
    myDonations:       'My Donations',
    adminPanel:        'Admin Panel',
    search:            'Search…',

    // ── Common ───────────────────────────────────────
    viewAll:           'View All',
    readMore:          'Read More',
    register:          'Register',
    free:              'Free',
    learnMore:         'Learn More',
    loading:           'Loading…',
    noResults:         'No results found',
    back:              'Back',
    close:             'Close',
    cancel:            'Cancel',
    save:              'Save',
    delete:            'Delete',
    edit:              'Edit',
    submit:            'Submit',
    sending:           'Sending…',
    required:          'Required',
    optional:          'Optional',
    allRightsReserved: 'All rights reserved.',
    memberPortal:      'Member Portal',
    joinCommunity:     'Join Community',
    becomeVolunteer:   'Become A Volunteer',
    meetVolunteers:    'Meet Volunteers',
    ourStory:          'Our Story',
    viewReports:       'View Reports',
    viewProject:       'View Project',
    viewAllProjects:   'View All Projects',
    viewAllEvents:     'View All Events',
    viewAllArticles:   'View All Articles',
    viewFullGallery:   'View Full Gallery',
    allArticles:       'All Articles',

    // ── Footer ───────────────────────────────────────
    stayConnected:     'Stay Connected',
    getVillageNews:    'Get village news & updates in your inbox',
    enterEmail:        'Enter your email address',
    subscribeBtn:      'Subscribe',
    thankYouSubscribed:'Thank you for subscribing!',
    explore:           'Explore',
    communitySection:  'Community',
    ourGallery:        'Our Gallery',
    aboutUsFooter:     'About Us',
    ourProjects:       'Our Projects',
    newsUpdates:       'News & Updates',
    upcomingEventsFooter: 'Upcoming Events',
    contactUs:         'Contact Us',
    diasporaNetwork:   'Diaspora Network',
    forum:             'Forum',
    scholarships:      'Scholarships',
    businessDirectory: 'Business Directory',
    mentorship:        'Mentorship',

    // ── Home ─────────────────────────────────────────
    heroTitle:         'Together We Build a Stronger Community',
    heroSub:           'Supporting Nkenkak-Ngiesang through education, health, and sustainable development.',
    globalDonors:      'Global Donors',
    activeProjects:    'Active Projects',
    countries:         'Countries',
    rootedInHeritage:  'Rooted in Heritage, Building for Tomorrow',
    aboutNNDC:         'About N-NDC',
    foundedLabel:      'Founded',
    membersLabel:      'Members',
    projectsLabel:     'Projects',
    orgFounded:        'Organisation Founded',
    firstProjects:     'First Projects Launched',
    growingImpact:     'Growing Impact',
    cultureLabel:      'Culture',
    communityLabel:    'Community',
    impactLabel:       'Impact',
    transparencyMsg:   'Full financial transparency since founding',
    transparencyDesc:  'Every XAF tracked and published after each project milestone.',
    upcomingEvents:    'Upcoming Events',
    joinNextEvent:     'Join Us at Our Next Event',
    featuredProjects:  'Featured Projects',
    realImpact:        'Real Impact, Real Village Stories',
    realImpactDesc:    'Every project is proposed, vetted, and funded by our community — 100% of donations go directly to the village.',
    giveYourTime:      'Give Your Time, Change a Life',
    giveYourTimeDesc:  'Skills, expertise, and presence matter just as much as money. Join our volunteer network and help build something lasting for the next generation.',
    makeADonation:     'Make a Donation Today',
    everyFCFA:         'Every FCFA matters. Choose an amount and contribute to the project closest to your heart.',
    latestNews:        'Latest News',
    fromOurVillage:    'From Our Village',
    communityVoices:   'Community Voices',
    whatLeadersSay:    'What Our Leaders Say',
    realStoriesDesc:   'Real stories from village residents, diaspora members and volunteers who are part of our journey.',
    yourVillageNeeds:  'Your Village Needs You',
    yourSkillsCanBuild:'Your Skills Can Build a Brighter Tomorrow',
    skillsDesc:        'Architects, doctors, teachers, engineers, IT professionals — your expertise can transform our village in ways money alone cannot.',
    activeVolunteers:  'Active Volunteers',
    hoursContributed:  'Hours Contributed',
    projectsSupported: 'Projects Supported',
    neverMissUpdate:   'Never Miss a Village Update',
    neverMissDesc:     'Get project milestones, event invitations, and community news delivered straight to your inbox.',
    youreSubscribed:   "You're subscribed! Welcome to the family.",
    noSpam:            'No spam. Unsubscribe anytime. Your privacy is respected.',
    lifeInPictures:    'Life in Nkenkak-Ngiesang in pictures',
    momentsCaptured:   '{total} moments captured from our village, events, and community projects.',
    globalCommunity:   'Global Community',
    homeIsWherever:    'Home is wherever you are',
    globalDesc:        'Members in 14+ countries stay connected, contribute, and help shape the future of Nkenkak-Ngiesang from wherever life takes them.',
    exploreDiaspora:   'Explore Diaspora Network',
    noUpcomingEvents:  'No upcoming events right now',
    checkBackSoon:     'Check back soon — community gatherings are being planned.',
    viewPastEvents:    'View Past Events',
    today:             'Today!',
    tomorrow:          'Tomorrow',
    inDays:            'In {n} days',
    registerNowFree:   'Register Now — Free',
    getTicketPrice:    'Get Ticket · {price} XAF',

    // ── Auth ─────────────────────────────────────────
    signIn:            'Sign In',
    welcomeBack:       'Welcome back to your community',
    emailAddress:      'Email Address',
    password:          'Password',
    forgotPassword:    'Forgot password?',
    signingIn:         'Signing in…',
    dontHaveAccount:   "Don't have an account?",
    createAccount:     'Create Account',
    joinToday:         'Join the Nkenkak-Ngiesang community today',
    firstName:         'First Name',
    lastName:          'Last Name',
    phoneWhatsapp:     'Phone / WhatsApp',
    country:           'Country',
    city:              'City',
    minChars:          'At least {n} characters',
    diasporaMember:    'I am a diaspora member (living outside Cameroon)',
    subscribeNewsletter: 'Subscribe to village newsletter',
    agreeTerms:        'I agree to the',
    communityTerms:    'Community Terms',
    creatingAccount:   'Creating account…',
    alreadyHaveAccount:'Already have an account?',
    invalidCredentials:'Invalid email or password',
    registrationFailed:'Registration failed',
    welcomeToast:      'Welcome back, {name}!',
    registerToast:     'Welcome to Nkenkak-Ngiesang! Check your email to verify.',

    // ── News ─────────────────────────────────────────
    latestNewsEyebrow: 'Latest News & Articles',
    keepReading:       'Keep Reading',
    relatedArticles:   'Related Articles',
    publishedOn:       'Published {date}',
    minRead:           '{n} min read',
    shareArticle:      'Share',
    noArticlesYet:     'No articles published yet — check back soon.',
    searchNews:        'Search articles…',
    allCategories:     'All',
    featuredBadge:     'Featured',

    // ── Events ───────────────────────────────────────
    eventDetails:      'Event Details',
    location:          'Location',
    dateTime:          'Date & Time',
    organiser:         'Organiser',
    ticketPrice:       'Ticket Price',
    freeEntry:         'Free Entry',
    onlineEvent:       'Online Event',
    registerForEvent:  'Register for this Event',
    addToCalendar:     'Add to Calendar',
    agenda:            'Agenda',
    attendees:         'Attendees',
    comments:          'Comments',
    waitlist:          'Waitlist',
    spotsLeft:         '{n} spots left',
    eventFull:         'Event Full',
    leaveComment:      'Leave a comment…',
    postComment:       'Post Comment',

    // ── Projects ─────────────────────────────────────
    raised:            'Raised',
    goal:              'Goal',
    funded:            'funded',
    donors:            'donors',
    daysLeft:          '{n} days left',
    completed:         'Completed',
    donateToProject:   'Donate to this Project',
    projectUpdates:    'Project Updates',
    projectGallery:    'Project Gallery',
    relatedProjects:   'Related Projects',
    searchProjects:    'Search projects…',
    allStatus:         'All',
    active:            'Active',
    inProgress:        'In Progress',
    noProjectsFound:   'No projects found',

    // ── Gallery ──────────────────────────────────────
    galleryArchive:    'Document Archive',
    filterByCategory:  'Filter by category or search',
    searchDocuments:   'Search documents by title or description…',
    totalDocuments:    'Total Documents',
    totalDownloads:    'Total Downloads',
    noDocumentsFound:  'No documents found',
    noDocumentsInCat:  'No documents in this category yet.',
    nothingMatched:    'Nothing matched "{q}".',
    uploadedFromAdmin: 'Documents can be uploaded from the Admin Panel.',
    download:          'Download',
    preview:           'Preview',
    opening:           'Opening…',
    searchGallery:     'Search gallery…',
    photos:            'Photos',
    videos:            'Videos',
    noPhotosYet:       'No photos yet',
    filterGallery:     'Filter',

    // ── Contact ──────────────────────────────────────
    getInTouch:        'Get in Touch',
    sendUsMessage:     'Send us a Message',
    yourName:          'Your Name',
    yourEmail:         'Your Email',
    subject:           'Subject',
    message:           'Message',
    sendMessage:       'Send Message',
    messageSent:       "Message sent! We'll get back to you soon.",
    officeAddress:     'Office Address',
    phoneNumber:       'Phone Number',
    emailUs:           'Email Us',
    followUs:          'Follow Us',

    // ── Culture ──────────────────────────────────────
    ourHeritage:       'Our Heritage',
    ourHistory:        'Our History',
    ourCulture:        'Our Culture & Traditions',
    ourMission:        'Our Mission',
    villageFounders:   'Village Founders',
    traditions:        'Traditions',
    language:          'Language',
    governance:        'Governance',

    // ── Diaspora ─────────────────────────────────────
    diasporaTitle:     'Diaspora Network',
    diasporaDesc:      'Connect with Nkenkak-Ngiesang members around the world',
    registerAsDiaspora:'Register as Diaspora Member',
    membersWorldwide:  'Members Worldwide',

    // ── Directory ────────────────────────────────────
    memberDirectory:   'Member Directory',
    searchMembers:     'Search members…',
    noMembersFound:    'No members found',
    joinedLabel:       'Joined',
    locationLabel:     'Location',

    // ── Memorial ─────────────────────────────────────
    inMemoriam:        'In Memoriam',
    rememberingOurLoved: 'Remembering Our Loved Ones',
    passedAway:        'Passed away',
    tributeMessage:    'Leave a tribute',

    // ── Mentorship ───────────────────────────────────
    mentorshipProgram: 'Mentorship Programme',
    findAMentor:       'Find a Mentor',
    becomeAMentor:     'Become a Mentor',
    expertise:         'Expertise',
    applyNow:          'Apply Now',
    mentorAvailable:   'Available',
    noMentorsFound:    'No mentors found',

    // ── Scholarships ─────────────────────────────────
    scholarshipsTitle: 'Scholarships',
    applyForScholarship: 'Apply for Scholarship',
    deadline:          'Deadline',
    eligibility:       'Eligibility',
    amount:            'Amount',
    apply:             'Apply',
    noScholarships:    'No scholarships available right now',

    // ── Jobs ─────────────────────────────────────────
    jobBoard:          'Jobs & Classifieds',
    postAJob:          'Post a Job',
    applyForJob:       'Apply',
    jobType:           'Job Type',
    salary:            'Salary',
    postedOn:          'Posted {date}',
    noJobsFound:       'No jobs found',
    fullTime:          'Full Time',
    partTime:          'Part Time',
    remote:            'Remote',
    contract:          'Contract',

    // ── Transparency ─────────────────────────────────
    financialTransparency: 'Financial Transparency',
    allFundsTracked:   'All funds are tracked and published',
    downloadReport:    'Download Report',
    totalRaised:       'Total Raised',
    totalSpent:        'Total Spent',
    balance:           'Balance',
    reportPeriod:      'Report Period',
    noReports:         'No reports published yet',

    // ── Wiki ─────────────────────────────────────────
    knowledgeWiki:     'Knowledge Wiki',
    contribute:        'Contribute',
    searchWiki:        'Search wiki…',
    lastUpdated:       'Last updated {date}',
    noArticles:        'No wiki articles yet',

    // ── Portal ───────────────────────────────────────
    welcomePortal:     'Welcome, {name}',
    yourContributions: 'Your Contributions',
    yourEvents:        'Your Events',
    yourDonations:     'Your Donations',
    notifications:     'Notifications',
    noNotifications:   'No new notifications',
    markAllRead:       'Mark all as read',
    settings:          'Settings',
    editProfile:       'Edit Profile',
    saveChanges:       'Save Changes',
    changePassword:    'Change Password',
    currentPassword:   'Current Password',
    newPassword:       'New Password',
    confirmPassword:   'Confirm Password',
    passwordUpdated:   'Password updated successfully',
    profileUpdated:    'Profile updated successfully',

    // ── Why Us section ───────────────────────────────
    communityLed:      'Community-Led, Zero Overhead',
    communityLedDesc:  'Unlike large NGOs, we are the community. Every project is proposed by a village member, approved by the council, and executed with full financial transparency.',
    fullyTransparent:  '100% Transparent',
    transparentDesc:   'Full financial reports published after every project milestone. No hidden fees.',
    communityGoverned: 'Community Governed',
    communityGovDesc:  'Projects are voted on by village elders, youth council, and diaspora members.',
    directImpact:      'Direct Impact',
    directImpactDesc:  'Funds go straight to contractors and suppliers in the village — zero bureaucracy.',
    diasporaInclusive: 'Diaspora Inclusive',
    diasporaIncDesc:   "Whether you're in Yaoundé or Paris, you have an equal voice in every decision.",

    // ── Notices ──────────────────────────────────────
    notices:           'Notices',
    officialNotices:   'Official Notices & Announcements',
    urgentNotice:      'Urgent',
    allNotices:        'All Notices',
    noNotices:         'No notices at this time',
    viewAllNotices:    'View All Notices',

    // ── Elections ────────────────────────────────────
    elections:         'Elections',
    voteNow:           'Vote Now',
    votingClosed:      'Voting Closed',
    results:           'Results',
    candidate:         'Candidate',
    totalVotes:        'Total Votes',
    yourVote:          'Your Vote',
    alreadyVoted:      'You have already voted',
    votingEnds:        'Voting ends {date}',

    // ── Live ─────────────────────────────────────────
    liveMeetings:      'Live Meetings',
    joinMeeting:       'Join Meeting',
    meetingLink:       'Meeting Link',
    noLiveMeetings:    'No live meetings scheduled',
    upcomingMeetings:  'Upcoming Meetings',
  },

  fr: {
    // ── Nav ──────────────────────────────────────────
    home:              'Accueil',
    aboutUs:           'À Propos',
    anthropology:      'Anthropologie',
    donation:          'Donation',
    allProjects:       'Tous les Projets',
    education:         'Éducation',
    health:            'Santé',
    infra:             'Infrastructure',
    pages:             'Pages',
    ourTeam:           'Notre Équipe',
    gallery:           'Galerie',
    faq:               'FAQ',
    diaspora:          'Carte Diaspora',
    volunteers:        'Bénévoles',
    events:            'Événements',
    news:              'Actualités',
    contact:           'Contact',
    donateNow:         'Faire un Don',
    login:             'Connexion',
    logout:            'Déconnexion',
    myDashboard:       'Mon Tableau de Bord',
    profile:           'Profil',
    myDonations:       'Mes Dons',
    adminPanel:        'Panneau Admin',
    search:            'Rechercher…',

    // ── Common ───────────────────────────────────────
    viewAll:           'Voir Tout',
    readMore:          'Lire Plus',
    register:          "S'inscrire",
    free:              'Gratuit',
    learnMore:         'En Savoir Plus',
    loading:           'Chargement…',
    noResults:         'Aucun résultat',
    back:              'Retour',
    close:             'Fermer',
    cancel:            'Annuler',
    save:              'Enregistrer',
    delete:            'Supprimer',
    edit:              'Modifier',
    submit:            'Envoyer',
    sending:           'Envoi en cours…',
    required:          'Obligatoire',
    optional:          'Facultatif',
    allRightsReserved: 'Tous droits réservés.',
    memberPortal:      'Espace Membre',
    joinCommunity:     'Rejoindre la Communauté',
    becomeVolunteer:   'Devenir Bénévole',
    meetVolunteers:    'Rencontrer les Bénévoles',
    ourStory:          'Notre Histoire',
    viewReports:       'Voir les Rapports',
    viewProject:       'Voir le Projet',
    viewAllProjects:   'Voir Tous les Projets',
    viewAllEvents:     'Voir Tous les Événements',
    viewAllArticles:   'Voir Tous les Articles',
    viewFullGallery:   'Voir la Galerie Complète',
    allArticles:       'Tous les Articles',

    // ── Footer ───────────────────────────────────────
    stayConnected:     'Restez Connecté',
    getVillageNews:    'Recevez les actualités du village dans votre boîte mail',
    enterEmail:        'Entrez votre adresse e-mail',
    subscribeBtn:      "S'abonner",
    thankYouSubscribed:'Merci pour votre inscription !',
    explore:           'Explorer',
    communitySection:  'Communauté',
    ourGallery:        'Notre Galerie',
    aboutUsFooter:     'À Propos',
    ourProjects:       'Nos Projets',
    newsUpdates:       'Actualités',
    upcomingEventsFooter: 'Événements à Venir',
    contactUs:         'Nous Contacter',
    diasporaNetwork:   'Réseau Diaspora',
    forum:             'Forum',
    scholarships:      'Bourses',
    businessDirectory: 'Annuaire des Entreprises',
    mentorship:        'Mentorat',

    // ── Home ─────────────────────────────────────────
    heroTitle:         'Ensemble, Construisons une Communauté Plus Forte',
    heroSub:           "Soutenir Nkenkak-Ngiesang à travers l'éducation, la santé et le développement durable.",
    globalDonors:      'Donateurs Mondiaux',
    activeProjects:    'Projets Actifs',
    countries:         'Pays',
    rootedInHeritage:  'Enracinés dans le Patrimoine, Construire pour Demain',
    aboutNNDC:         'À Propos du N-NDC',
    foundedLabel:      'Fondé',
    membersLabel:      'Membres',
    projectsLabel:     'Projets',
    orgFounded:        "Fondation de l'Organisation",
    firstProjects:     'Premiers Projets Lancés',
    growingImpact:     'Impact Croissant',
    cultureLabel:      'Culture',
    communityLabel:    'Communauté',
    impactLabel:       'Impact',
    transparencyMsg:   'Transparence financière totale depuis la fondation',
    transparencyDesc:  'Chaque XAF est suivi et publié après chaque étape du projet.',
    upcomingEvents:    'Événements à Venir',
    joinNextEvent:     'Rejoignez-nous au Prochain Événement',
    featuredProjects:  'Projets en Vedette',
    realImpact:        'Un Impact Réel, de Vraies Histoires Villageoises',
    realImpactDesc:    "Chaque projet est proposé, évalué et financé par notre communauté — 100 % des dons vont directement au village.",
    giveYourTime:      'Donnez Votre Temps, Changez Une Vie',
    giveYourTimeDesc:  "Les compétences, l'expertise et la présence comptent autant que l'argent. Rejoignez notre réseau de bénévoles.",
    makeADonation:     'Faire un Don Aujourd\'hui',
    everyFCFA:         "Chaque FCFA compte. Choisissez un montant et contribuez au projet le plus proche de votre cœur.",
    latestNews:        'Dernières Actualités',
    fromOurVillage:    'De Notre Village',
    communityVoices:   'Voix de la Communauté',
    whatLeadersSay:    'Ce que Disent Nos Leaders',
    realStoriesDesc:   "De vraies histoires de résidents du village, de membres de la diaspora et de bénévoles qui font partie de notre voyage.",
    yourVillageNeeds:  'Votre Village a Besoin de Vous',
    yourSkillsCanBuild:"Vos Compétences Peuvent Construire un Avenir Plus Lumineux",
    skillsDesc:        "Architectes, médecins, enseignants, ingénieurs, professionnels IT — votre expertise peut transformer notre village.",
    activeVolunteers:  'Bénévoles Actifs',
    hoursContributed:  'Heures Contribuées',
    projectsSupported: 'Projets Soutenus',
    neverMissUpdate:   'Ne Manquez Jamais une Mise à Jour du Village',
    neverMissDesc:     'Recevez les jalons des projets, invitations aux événements et actualités communautaires dans votre boîte mail.',
    youreSubscribed:   'Vous êtes inscrit ! Bienvenue dans la famille.',
    noSpam:            'Pas de spam. Désabonnez-vous à tout moment. Votre vie privée est respectée.',
    lifeInPictures:    'La Vie à Nkenkak-Ngiesang en Images',
    momentsCaptured:   '{total} moments capturés de notre village, événements et projets communautaires.',
    globalCommunity:   'Communauté Mondiale',
    homeIsWherever:    'Chez soi, où que vous soyez',
    globalDesc:        "Des membres dans 14+ pays restent connectés, contribuent et façonnent l'avenir de Nkenkak-Ngiesang.",
    exploreDiaspora:   'Explorer le Réseau Diaspora',
    noUpcomingEvents:  "Aucun événement à venir pour l'instant",
    checkBackSoon:     'Revenez bientôt — des rassemblements communautaires sont en cours de planification.',
    viewPastEvents:    'Voir les Événements Passés',
    today:             "Aujourd'hui !",
    tomorrow:          'Demain',
    inDays:            'Dans {n} jours',
    registerNowFree:   "S'inscrire — Gratuit",
    getTicketPrice:    'Obtenir un Billet · {price} XAF',

    // ── Auth ─────────────────────────────────────────
    signIn:            'Se Connecter',
    welcomeBack:       'Bienvenue dans votre communauté',
    emailAddress:      'Adresse E-mail',
    password:          'Mot de Passe',
    forgotPassword:    'Mot de passe oublié ?',
    signingIn:         'Connexion en cours…',
    dontHaveAccount:   "Vous n'avez pas de compte ?",
    createAccount:     'Créer un Compte',
    joinToday:         "Rejoignez la communauté Nkenkak-Ngiesang aujourd'hui",
    firstName:         'Prénom',
    lastName:          'Nom de Famille',
    phoneWhatsapp:     'Téléphone / WhatsApp',
    country:           'Pays',
    city:              'Ville',
    minChars:          'Au moins {n} caractères',
    diasporaMember:    'Je suis un membre de la diaspora (vivant hors du Cameroun)',
    subscribeNewsletter: 'S\'abonner à la newsletter du village',
    agreeTerms:        "J'accepte les",
    communityTerms:    'Conditions Communautaires',
    creatingAccount:   'Création du compte…',
    alreadyHaveAccount:'Vous avez déjà un compte ?',
    invalidCredentials:'E-mail ou mot de passe invalide',
    registrationFailed:'Échec de l\'inscription',
    welcomeToast:      'Bon retour, {name} !',
    registerToast:     'Bienvenue à Nkenkak-Ngiesang ! Vérifiez votre e-mail pour confirmer.',

    // ── News ─────────────────────────────────────────
    latestNewsEyebrow: 'Dernières Actualités & Articles',
    keepReading:       'Continuer la Lecture',
    relatedArticles:   'Articles Connexes',
    publishedOn:       'Publié le {date}',
    minRead:           '{n} min de lecture',
    shareArticle:      'Partager',
    noArticlesYet:     "Aucun article publié pour l'instant — revenez bientôt.",
    searchNews:        'Rechercher des articles…',
    allCategories:     'Tout',
    featuredBadge:     'En Vedette',

    // ── Events ───────────────────────────────────────
    eventDetails:      "Détails de l'Événement",
    location:          'Lieu',
    dateTime:          'Date & Heure',
    organiser:         'Organisateur',
    ticketPrice:       'Prix du Billet',
    freeEntry:         'Entrée Gratuite',
    onlineEvent:       'Événement en Ligne',
    registerForEvent:  "S'inscrire à cet Événement",
    addToCalendar:     'Ajouter au Calendrier',
    agenda:            'Agenda',
    attendees:         'Participants',
    comments:          'Commentaires',
    waitlist:          "Liste d'Attente",
    spotsLeft:         '{n} places restantes',
    eventFull:         'Événement Complet',
    leaveComment:      'Laisser un commentaire…',
    postComment:       'Publier le Commentaire',

    // ── Projects ─────────────────────────────────────
    raised:            'Collecté',
    goal:              'Objectif',
    funded:            'financé',
    donors:            'donateurs',
    daysLeft:          '{n} jours restants',
    completed:         'Terminé',
    donateToProject:   'Faire un Don à ce Projet',
    projectUpdates:    'Mises à Jour du Projet',
    projectGallery:    'Galerie du Projet',
    relatedProjects:   'Projets Connexes',
    searchProjects:    'Rechercher des projets…',
    allStatus:         'Tout',
    active:            'Actif',
    inProgress:        'En Cours',
    noProjectsFound:   'Aucun projet trouvé',

    // ── Gallery / Documents ──────────────────────────
    galleryArchive:    'Archive de Documents',
    filterByCategory:  'Filtrer par catégorie ou rechercher',
    searchDocuments:   'Rechercher des documents par titre ou description…',
    totalDocuments:    'Total des Documents',
    totalDownloads:    'Total des Téléchargements',
    noDocumentsFound:  'Aucun document trouvé',
    noDocumentsInCat:  'Aucun document dans cette catégorie.',
    nothingMatched:    'Aucun résultat pour « {q} ».',
    uploadedFromAdmin: "Les documents peuvent être téléchargés depuis le Panneau d'Administration.",
    download:          'Télécharger',
    preview:           'Aperçu',
    opening:           'Ouverture…',
    searchGallery:     'Rechercher dans la galerie…',
    photos:            'Photos',
    videos:            'Vidéos',
    noPhotosYet:       'Pas encore de photos',
    filterGallery:     'Filtrer',

    // ── Contact ──────────────────────────────────────
    getInTouch:        'Prendre Contact',
    sendUsMessage:     'Envoyez-nous un Message',
    yourName:          'Votre Nom',
    yourEmail:         'Votre E-mail',
    subject:           'Sujet',
    message:           'Message',
    sendMessage:       'Envoyer le Message',
    messageSent:       'Message envoyé ! Nous vous répondrons bientôt.',
    officeAddress:     'Adresse du Bureau',
    phoneNumber:       'Numéro de Téléphone',
    emailUs:           'E-mail',
    followUs:          'Suivez-nous',

    // ── Culture ──────────────────────────────────────
    ourHeritage:       'Notre Patrimoine',
    ourHistory:        'Notre Histoire',
    ourCulture:        'Notre Culture & Traditions',
    ourMission:        'Notre Mission',
    villageFounders:   'Fondateurs du Village',
    traditions:        'Traditions',
    language:          'Langue',
    governance:        'Gouvernance',

    // ── Diaspora ─────────────────────────────────────
    diasporaTitle:     'Réseau Diaspora',
    diasporaDesc:      'Connectez-vous avec les membres de Nkenkak-Ngiesang dans le monde entier',
    registerAsDiaspora:"S'inscrire en tant que Membre de la Diaspora",
    membersWorldwide:  'Membres dans le Monde',

    // ── Directory ────────────────────────────────────
    memberDirectory:   'Annuaire des Membres',
    searchMembers:     'Rechercher des membres…',
    noMembersFound:    'Aucun membre trouvé',
    joinedLabel:       'Inscrit',
    locationLabel:     'Localisation',

    // ── Memorial ─────────────────────────────────────
    inMemoriam:        'In Memoriam',
    rememberingOurLoved: 'En Mémoire de Nos Êtres Chers',
    passedAway:        'Décédé(e) le',
    tributeMessage:    'Laisser un hommage',

    // ── Mentorship ───────────────────────────────────
    mentorshipProgram: 'Programme de Mentorat',
    findAMentor:       'Trouver un Mentor',
    becomeAMentor:     'Devenir Mentor',
    expertise:         'Expertise',
    applyNow:          'Postuler Maintenant',
    mentorAvailable:   'Disponible',
    noMentorsFound:    'Aucun mentor trouvé',

    // ── Scholarships ─────────────────────────────────
    scholarshipsTitle: 'Bourses d\'Études',
    applyForScholarship: 'Postuler pour une Bourse',
    deadline:          "Date Limite",
    eligibility:       'Éligibilité',
    amount:            'Montant',
    apply:             'Postuler',
    noScholarships:    "Aucune bourse disponible pour l'instant",

    // ── Jobs ─────────────────────────────────────────
    jobBoard:          'Emplois & Petites Annonces',
    postAJob:          'Publier une Offre',
    applyForJob:       'Postuler',
    jobType:           "Type d'Emploi",
    salary:            'Salaire',
    postedOn:          'Publié le {date}',
    noJobsFound:       'Aucune offre trouvée',
    fullTime:          'Temps Plein',
    partTime:          'Temps Partiel',
    remote:            'Télétravail',
    contract:          'Contrat',

    // ── Transparency ─────────────────────────────────
    financialTransparency: 'Transparence Financière',
    allFundsTracked:   'Tous les fonds sont suivis et publiés',
    downloadReport:    'Télécharger le Rapport',
    totalRaised:       'Total Collecté',
    totalSpent:        'Total Dépensé',
    balance:           'Solde',
    reportPeriod:      'Période du Rapport',
    noReports:         'Aucun rapport publié pour le moment',

    // ── Wiki ─────────────────────────────────────────
    knowledgeWiki:     'Wiki Communautaire',
    contribute:        'Contribuer',
    searchWiki:        'Rechercher dans le wiki…',
    lastUpdated:       'Dernière mise à jour le {date}',
    noArticles:        'Aucun article wiki pour le moment',

    // ── Portal ───────────────────────────────────────
    welcomePortal:     'Bienvenue, {name}',
    yourContributions: 'Vos Contributions',
    yourEvents:        'Vos Événements',
    yourDonations:     'Vos Dons',
    notifications:     'Notifications',
    noNotifications:   'Aucune nouvelle notification',
    markAllRead:       'Tout marquer comme lu',
    settings:          'Paramètres',
    editProfile:       'Modifier le Profil',
    saveChanges:       'Enregistrer les Modifications',
    changePassword:    'Changer le Mot de Passe',
    currentPassword:   'Mot de Passe Actuel',
    newPassword:       'Nouveau Mot de Passe',
    confirmPassword:   'Confirmer le Mot de Passe',
    passwordUpdated:   'Mot de passe mis à jour avec succès',
    profileUpdated:    'Profil mis à jour avec succès',

    // ── Why Us ───────────────────────────────────────
    communityLed:      'Dirigé par la Communauté, Zéro Frais Généraux',
    communityLedDesc:  "Contrairement aux grandes ONG, nous sommes la communauté. Chaque projet est proposé par un habitant du village, approuvé par le conseil, et exécuté avec une transparence financière totale.",
    fullyTransparent:  '100% Transparent',
    transparentDesc:   'Rapports financiers complets publiés après chaque étape de projet. Aucuns frais cachés.',
    communityGoverned: 'Gouverné par la Communauté',
    communityGovDesc:  "Les projets sont votés par les anciens du village, le conseil des jeunes et les membres de la diaspora.",
    directImpact:      'Impact Direct',
    directImpactDesc:  "Les fonds vont directement aux entrepreneurs et fournisseurs du village — zéro bureaucratie.",
    diasporaInclusive: 'Inclusif pour la Diaspora',
    diasporaIncDesc:   "Que vous soyez à Yaoundé ou à Paris, vous avez une voix égale dans chaque décision.",

    // ── Notices ──────────────────────────────────────
    notices:           'Avis',
    officialNotices:   'Avis Officiels & Annonces',
    urgentNotice:      'Urgent',
    allNotices:        'Tous les Avis',
    noNotices:         "Aucun avis pour l'instant",
    viewAllNotices:    'Voir Tous les Avis',

    // ── Elections ────────────────────────────────────
    elections:         'Élections',
    voteNow:           'Voter Maintenant',
    votingClosed:      'Vote Fermé',
    results:           'Résultats',
    candidate:         'Candidat',
    totalVotes:        'Total des Votes',
    yourVote:          'Votre Vote',
    alreadyVoted:      'Vous avez déjà voté',
    votingEnds:        'Le vote se termine le {date}',

    // ── Live ─────────────────────────────────────────
    liveMeetings:      'Réunions en Direct',
    joinMeeting:       'Rejoindre la Réunion',
    meetingLink:       'Lien de la Réunion',
    noLiveMeetings:    'Aucune réunion en direct prévue',
    upcomingMeetings:  'Réunions à Venir',
  },
}

const LanguageContext = createContext(null)

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState(() => localStorage.getItem('lang') || 'en')

  const toggle = () => {
    const next = lang === 'en' ? 'fr' : 'en'
    setLang(next)
    localStorage.setItem('lang', next)
  }

  // Supports interpolation: t('inDays', { n: 5 }) → "In 5 days" / "Dans 5 jours"
  const t = (key, vars = {}) => {
    let str = translations[lang][key] ?? translations['en'][key] ?? key
    return Object.entries(vars).reduce((s, [k, v]) => s.replace(`{${k}}`, v), str)
  }

  return (
    <LanguageContext.Provider value={{ lang, toggle, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  const ctx = useContext(LanguageContext)
  if (!ctx) throw new Error('useLanguage must be used within LanguageProvider')
  return ctx
}
